import Sidebar from "../components/Sidebar";
import Footer from "../components/Footer";
import ContForm from "../components/contribute/form";
import Head from "next/head";
import { Navbar } from "../components";
import { useState } from "react";

function Contribute() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="">
      <Head>
        <title>ClimeCheck UI</title>
        <meta
          name="Clime Check Web app"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
      <main className="main p-8 flex w-screen m-auto justify-center items-center">
        <ContForm />
      </main>
      <Footer />
    </div>
  );
}

export default Contribute;
