import Sidebar from "../components/Sidebar";
import Footer from "../components/Footer";
import ContForm from "../components/contribute/form";
import Head from "next/head";
import { Navbar } from "../components";
import { useState } from "react";

function Contribute() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div>
      <Head>
        <title>ClimeCheck UI || Contribute</title>
        <meta
          name="Clime Check Web app"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar isOpen={isOpen} setIsOpen={setIsOpen} />
      <div className="px-12">
        <Navbar isOpen={isOpen} setIsOpen={setIsOpen} textColor="black" />
        <main className="main flex w-screen m-auto justify-center items-center">
          <ContForm />
        </main>
      </div>
    </div>
  );
}

export default Contribute;
