import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Timeline from '../components/Timeline'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ClimeCheck UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="viewport-fit=cover" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
        <Timeline />
      </main>

      <footer className='footer'>
        <Footer />
      </footer>
    </div>
  )
}
