import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Timeline from "../components/Timeline";
import { Hero, Navbar, Mapbase, WhyClime } from "../components";
import styles from "../styles/Home.module.scss";

import Sidebar from "../components/Sidebar";
import { useState } from "react";

export const getServerSideProps = async () => {
  const { co2 = 0 } = await (
    await fetch("https://global-warming.org/api/co2-api/")
  )?.json();
  const { result = 0 } = await (
    await fetch("https://global-warming.org/api/temperature-api")
  )?.json();

  const res = await fetch("https://climate.nasa.gov/api/v1/vital_signs/5/");
  const { value = 0 } = await res.json();

  const { trend } = co2.pop();
  const { station } = result.pop();

  if (!result || !trend || !station) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      data: { station, trend, value },
    },
  };
};

export default function Home({ data }) {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div>
      <Head>
        <title>ClimeCheck UI</title>
        <meta
          name="Clime Check Web app"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar isOpen={isOpen} setIsOpen={setIsOpen} />
      <div className={styles.container}>
        <div className={styles.wrapper}>
          <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
          <Hero data={data} />
        </div>
        <Mapbase />
        <WhyClime />
      </div>
      <main className="main w-screen m-auto justify-center items-center">
        <Timeline />
      </main>

      <Footer />
    </div>
  );
}
